### ISSUE TITLE
Parsing Int64 leads to crash

### ISSUE THREAD

**Issue by Belorus** [xoofx/SharpYaml#14]
Hi,

First of all - thanks for amazing library. 

Reallife use case: Merging app configs with long app_ids in content and loading resulting config.

Smallest repro:

    var sr = new Serializer(new SerializerSettings() {EmitTags = false});
    var map = sr.Deserialize<Dictionary<object, object>>("key: \"12345678901\"");
    var newYaml = sr.Serialize(map);
    var map2 = sr.Deserialize<Dictionary<object, object>>(newYaml);

Unhandled Exception: SharpYaml.YamlException: (Lin: 10, Col: 21, Chr: 625) - (Lin: 10, Col: 36, Chr: 640): Error while deserializing node [Scalar [anchor = , tag = , value = 169545139744270, style = Plain, isPlainImplicit = True, isQuotedImplicit = False]] ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at SharpYaml.Schemas.CoreSchema.<PrepareScalarRules>b__14(Match m)
   at SharpYaml.Schemas.SchemaBase.ScalarResolutionRule`1.Decode(Match m)
   at SharpYaml.Schemas.SchemaBase.TryParse(Scalar scalar, Boolean parseValue, String& defaultTag, Object& value)
   at SharpYaml.Schemas.FailsafeSchema.TryParse(Scalar scalar, Boolean parseValue, String& defaultTag, Object& value)
   at SharpYaml.Serialization.Serializers.PrimitiveSerializer.ConvertFrom(ObjectContext& context, Scalar scalar)
   at SharpYaml.Serialization.Serializers.ScalarSerializerBase.ReadYaml(ObjectContext& objectContext)
   at SharpYaml.Serialization.Serializers.RoutingSerializer.ReadYaml(ObjectContext& objectContext)
   at SharpYaml.Serialization.Serializers.TagTypeSerializer.ReadYaml(ObjectContext& objectContext)
   at SharpYaml.Serialization.Serializers.AnchorSerializer.ReadYaml(ObjectContext& objectContext)
   at SharpYaml.Serialization.SerializerContext.ReadYaml(Object value, Type expectedType)

**Comment by xoofx** [comment]
Thanks for report. Good catch.

**Comment by sergey-tihon** [comment]
It is possible to fix it through `SerializerSettings`? I have the same issue https://github.com/sergey-tihon/SwaggerProvider/pull/11

**Comment by biz0n** [comment]
Replacing line 68 with these 2 lines fixes the issue, but slightly breaks BW compatibility for guys that expect int for value that has 10 digits (this fix will return long)


            AddScalarRule<int>("!!int", @"([-+]?(0|[1-9][0-9_]{0,8}))", m => Convert.ToInt32(m.Value.Replace("_", ""), CultureInfo.InvariantCulture), null);
			AddScalarRule<long>("!!int", @"([-+]?(0|[1-9][0-9_]{9,17}))", m => Convert.ToInt64(m.Value.Replace("_", ""), CultureInfo.InvariantCulture), null);

**Comment by xoofx** [comment]
This is fixed.
